version: "3.9"

networks:
  host-bridge-net:
    driver: bridge

services:
  simulateqcd:
    container_name: simulateqcd
    image: simulateqcd/simulateqcd:latest
    build:
      dockerfile: podman-build/Dockerfile
      env_file: .env
    networks:
      - host-bridge-net
    env_file: .env
    command: /bin/bash