version: "3.9"

networks:
  host-bridge-net:
    driver: bridge

services:
  simulateqcd:
    container_name: simulateqcd
    image: simulateqcd/simulateqcd:latest
    build:
      dockerfile: podman-build/Dockerfile
      args:
        - CORES=${CORES}
        - RHEL_VERSION=${RHEL_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    networks:
      - host-bridge-net
    env_file: .env
    command: /bin/bash